/* Transport and reconnection are isolated from game rendering. No keystrokes are sent. */
window.FriendService=class {
 constructor(onState,onConnection){this.onState=onState;this.onConnection=onConnection;this.room=null;this.offset=0;this.timer=null;this.busy=false;this.polling=false;this.suspended=false;this.apiResolution=null;this.key='country-memory-friend-session-v1';try{this.session=JSON.parse(localStorage.getItem(this.key)||'null');}catch{this.session=null;}const allowedApis=[window.FRIENDS_API,window.FRIENDS_API_FALLBACK].filter(Boolean);this.api=allowedApis.includes(this.session?.api)?this.session.api:null;window.addEventListener('online',()=>this.poll());document.addEventListener('visibilitychange',()=>{if(!document.hidden)this.poll();});}
 now(){return Date.now()+this.offset;}
 save(){try{if(this.session)localStorage.setItem(this.key,JSON.stringify(this.session));else localStorage.removeItem(this.key);}catch{}}
 async resolveApi(){if(this.api)return this.api;const fallback=window.FRIENDS_API_FALLBACK;if(!fallback)return this.api=FRIENDS_API;if(!this.apiResolution)this.apiResolution=(async()=>{for(const candidate of [...new Set([FRIENDS_API,fallback])]){try{const response=await fetch(candidate+'/health',{headers:{Accept:'application/json'},cache:'no-store',signal:AbortSignal.timeout(candidate===FRIENDS_API?1800:10000)});const data=await response.json();if(response.ok&&data?.ok)return this.api=candidate;}catch{}}throw new Error('No friends service is reachable.');})().finally(()=>{this.apiResolution=null;});return this.apiResolution;}
 async request(path,input,authenticated=true){let started,response;try{const api=await this.resolveApi();started=Date.now();response=await fetch(api+path,{method:input?'POST':'GET',headers:{...(input?{'Content-Type':'application/json'}:{}),...(authenticated&&this.session?.token?{Authorization:'Bearer '+this.session.token}:{})},body:input?JSON.stringify(input):undefined,signal:AbortSignal.timeout(10000)});}catch{const reconnecting=Boolean(this.session);this.onConnection(reconnecting?'RECONNECTING · Check your connection.':'PLAY WITH FRIENDS UNAVAILABLE · Check your connection.');throw new Error(reconnecting?'Connection lost. Reconnecting…':'Could not connect to Play with Friends. Check your connection and retry.');}let data;try{data=await response.json();}catch{throw new Error('The friends service is not available yet. Please retry shortly.');}if(data.serverNow)this.offset=data.serverNow-(started+Date.now())/2;if(!response.ok){const error=new Error(data.message||'Please retry.');error.code=data.error;throw error;}this.onConnection('');return data;}
 accept(data){if(this.room?.code===data.code&&data.revision<this.room.revision)return this.room;this.room=data;this.onState(data);if(this.session&&!this.suspended){clearTimeout(this.timer);let delay=document.hidden?8000:1500;const s=data.game;const due=s?.feedbackUntil||(!s?.currentQuestion?.resolved?s?.currentQuestion?.deadline:null)||s?.startedAt;if(due&&due>this.now())delay=Math.min(delay,Math.max(80,due-this.now()+30));if(s?.deadline&&s.deadline>this.now())delay=Math.min(delay,Math.max(80,s.deadline-this.now()+30));this.timer=setTimeout(()=>this.poll(),delay);}return data;}
 async create(name,challenge=null){const data=await this.request(challenge?'/challenges':'/rooms',{name,...(challenge||{})},false);this.session={code:data.code,token:data.token,api:this.api};this.save();return this.accept(data);}
 async inspect(code){return this.request('/rooms/'+encodeURIComponent(code),null,false);}
 async join(code,name){const data=await this.request('/rooms/'+encodeURIComponent(code),{action:'join',name},false);this.session={code:data.code,token:data.token,api:this.api};this.save();return this.accept(data);}
 async poll(){if(!this.session||this.polling||this.suspended)return;this.polling=true;try{this.accept(await this.request('/rooms/'+this.session.code));}catch(e){this.onConnection(e.message);if(['PLAYER_REMOVED','ROOM_EXPIRED','ROOM_NOT_FOUND'].includes(e.code)){clearTimeout(this.timer);this.onState({error:e.code,message:e.message});}else if(!this.suspended)this.timer=setTimeout(()=>this.poll(),2500);}finally{this.polling=false;}}
 async action(action,fields={}){if(!this.session)throw new Error('Join a room first.');const payload={action,...fields};try{return this.accept(await this.request('/rooms/'+this.session.code,payload));}catch(e){if(e.message.includes('Reconnecting')&&action==='answer'){try{return this.accept(await this.request('/rooms/'+this.session.code,payload));}catch{}}await this.poll();throw e;}}
 async leave(){try{await this.action('leave');}finally{clearTimeout(this.timer);this.session=null;this.room=null;this.save();}}
 suspend(){this.suspended=true;clearTimeout(this.timer);}
 resume(){this.suspended=false;return this.poll();}
 invite(){const code=this.session?.code||this.room?.code||'';return window.CountryMemoryRetained?.getHostedInviteUrl?.(code)||location.origin+location.pathname+'?room='+encodeURIComponent(code);}
};
