(function(){
 function boot(){if(!window.gameController)return setTimeout(boot,100);
 const app=document.querySelector('.app');let panel=document.createElement('section');panel.id='friendsPanel';panel.hidden=true;panel.setAttribute('aria-label','Play with friends');app.append(panel);
 const menu=document.querySelector('.game-choices');const entry=document.createElement('button');entry.type='button';entry.id='playFriends';entry.textContent='Play With Friends ↗';menu.before(entry);
 const board=document.createElement('details');board.id='liveBoard';board.hidden=true;board.innerHTML='<summary>LIVE STANDINGS</summary><div id="liveRows"></div>';document.querySelector('.map-shell').append(board);
 const countdown=document.createElement('div');countdown.id='friendCountdown';countdown.hidden=true;countdown.setAttribute('role','status');document.querySelector('.map-shell').append(countdown);
 const connection=document.createElement('div');connection.id='friendConnection';connection.setAttribute('role','status');connection.hidden=true;app.append(connection);
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let latest=null,renderKey='',pendingReplay=null,submitBusy=false,questionShownAt=0,questionKey=null,activeGameKey=null,noticeAt=0,lastLeader=null,lastEvent=null;
 const hosted=window.top!==window;
 const service=new FriendService(render,text=>{connection.textContent=text;connection.hidden=!text;if(text&&latest?.game?.gameStatus==='playing')gameController.blockRemote(true);});
 const titles={conquest:'World Conquest',find:'Find the Country',capital:'Capital Clash'};
 const modeLabels={relaxed:'Relaxed',sudden:'Sudden Death',sprint:'Sprint · 3 min',blitz:'Blitz · 60 sec',continent:'Continent',standard:'Standard',classic:'Classic'};
 function shell(content){panel.hidden=false;panel.innerHTML='<div class="friend-heading"><span class="eyebrow">PLAY WITH FRIENDS</span></div>'+content+'<p id="friendError" role="status"></p>';}
 function error(e){let el=document.querySelector('#friendError');if(!el){panel.hidden=false;panel.innerHTML+='<p id="friendError" role="status"></p>';el=document.querySelector('#friendError');}el.textContent=e.message||String(e);}
 function bind(id,fn){document.getElementById(id)?.addEventListener('click',async e=>{e.currentTarget.disabled=true;try{await fn();}catch(err){error(err);}finally{if(e.target.isConnected)e.target.disabled=false;}});}
 function nameValue(){return document.getElementById('friendName')?.value||'';}
 function nameField(){return '<label>Your name<input id="friendName" maxlength="20" autocomplete="nickname" placeholder="Enter your name"></label>';}
 function home(){pendingReplay=null;panel.hidden=false;board.hidden=true;renderKey='';shell('<h2>Send a link.<br>Play together.</h2><p>Private rooms. 2–8 players. No accounts.</p>'+nameField()+'<button id="createFriendRoom" class="primary-button">Create Room</button><label>Room code<input id="joinCode" placeholder="GEO…" maxlength="12" autocapitalize="characters"></label><button id="joinFriendRoom">Join Room</button>'+(service.session?'<button id="activeFriendRoom">My Active Room</button>':'')+'<button id="backSolo">Back to solo</button>');bind('createFriendRoom',()=>service.create(nameValue()));bind('joinFriendRoom',()=>joinScreen(document.getElementById('joinCode').value.trim().toUpperCase(),nameValue()));bind('activeFriendRoom',()=>service.poll());bind('backSolo',()=>{if(!window.CountryMemoryRetained?.requestHostNavigation({type:'home'}))panel.hidden=true;});}
 async function joinScreen(code,name=''){if(!/^[A-Z0-9]{6,12}$/.test(code))throw new Error('Enter the room code from your invite.');if(service.session?.code===code){await service.poll();return;}const data=await service.inspect(code);const playing=data.kind==='live'&&['COUNTDOWN','PLAYING'].includes(data.state);shell(`<h2>${esc(data.hostName)} ${data.kind==='challenge'?'challenged':'invited'} you</h2><p>${esc(titles[data.config.family])} · ${esc(modeLabels[data.config.variant]||data.config.variant)}</p><p>${data.players.length} / 8 players</p>`+(playing?'<h3>MATCH IN PROGRESS</h3><p>Wait here for the next round.</p><button id="refreshInvite">Wait / Refresh lobby</button>':nameField()+'<button id="acceptInvite" class="primary-button">'+(data.kind==='challenge'?'Join Challenge':'Join Room')+'</button>')+'<button id="newRoom">Create New Room</button>');if(document.getElementById('friendName'))document.getElementById('friendName').value=name;bind('acceptInvite',()=>service.join(code,nameValue()));bind('refreshInvite',()=>joinScreen(code));bind('newRoom',home);}
 function options(list,value){return list.map(([v,t])=>`<option value="${esc(v)}"${v===value?' selected':''}>${esc(t)}</option>`).join('');}
 function standings(data){return data.standings.map((p,i)=>`<div class="friend-standing${p.id===data.you?' is-you':''}"><b>${p.dnf?'DNF':p.rank}</b><span>${esc(p.name)}${p.id===data.you?' · you':''}</span><strong>${p.score.toLocaleString()}</strong><small>${p.finished?'Finished':data.config.family==='conquest'?p.correct+' found':'Q '+p.progress+(data.config.variant==='blitz'?'':' / '+data.config.questionCount)}</small></div>`).join('');}
 function lobby(data){const host=data.hostPlayerId===data.you,me=data.players.find(p=>p.id===data.you);const variants=data.config.family==='conquest'?['sprint','blitz','continent']:data.config.family==='find'?['standard','blitz','continent']:['classic','blitz','continent'];const allReady=data.players.length>=2&&data.players.every(p=>p.connected&&p.ready);
 const players=data.players.map((p,i)=>`<div class="friend-player"><span class="player-avatar">${['🌍','🧭','🚩','🗺️','✈️','🌐','📍','🏛️'][i]}</span><span>${esc(p.name)}${p.id===data.hostPlayerId?' <small>HOST</small>':''}</span><b>${!p.connected?'Offline':p.ready?'Ready':'Not ready'}</b>${host&&p.id!==data.you?`<button class="remove-player" data-player="${esc(p.id)}" aria-label="Remove ${esc(p.name)}">×</button>`:''}</div>`).join('');
 shell(`<h2>Friend room <span class="room-code">${esc(data.code)}</span></h2><p>${data.players.length} / 8 players</p><div class="friend-players">${players}</div><div class="friend-settings"><label>Game<select id="roomGame"${host?'':' disabled'}>${options(Object.entries(titles),data.config.family)}</select></label><label>Mode<select id="roomMode"${host?'':' disabled'}>${options(variants.map(x=>[x,modeLabels[x]]),data.config.variant)}</select></label>${data.config.family!=='conquest'?`<label>Difficulty<select id="roomDifficulty"${host?'':' disabled'}>${options(['easy','medium','hard','expert'].map(x=>[x,x]),data.config.difficulty)}</select></label><label>Time per question<select id="roomQuestionTime"${host?'':' disabled'}>${options([[30,'30 seconds'],[20,'20 seconds'],[15,'15 seconds'],[10,'10 seconds · challenging']].map(([v,t])=>[String(v),t]),String(data.config.questionTime||20))}</select></label>`:''}${data.config.variant==='continent'?`<label>Continent<select id="roomContinent"${host?'':' disabled'}>${options(['Africa','Asia','Europe','North America','South America','Oceania'].map(x=>[x,x]),data.config.region)}</select></label>`:''}${data.config.family!=='conquest'&&data.config.variant!=='blitz'?`<label>Questions<select id="roomQuestions"${host?'':' disabled'}>${options([10,20,30].map(x=>[String(x),String(x)]),String(data.config.questionCount))}</select></label>`:''}</div><p class="friend-note">${data.config.family==='conquest'&&data.config.variant==='continent'?'Continent games run for 3 minutes. ':''}Everyone receives the same rules and question order.</p><button id="setReady" class="primary-button">${me?.ready?'Not Ready':'Ready'}</button>${host?`<button id="startMatch"${allReady?'':' disabled'}>Start Game</button>`:'<p>Waiting for host to start.</p>'}<div class="share-actions"><button id="copyInvite">Copy Invite Link</button>${navigator.share?'<button id="nativeShare">Share</button>':''}</div><input class="invite-link" aria-label="Invite link" readonly value="${esc(service.invite())}"><button id="leaveFriendRoom">Leave Room</button>${host?'<button id="closeFriendRoom">Close Room</button>':''}${data.notice?`<p role="status">${esc(data.notice)}</p>`:''}`);
 bind('setReady',()=>service.action('ready',{ready:!me.ready}));bind('startMatch',()=>service.action('start'));bind('closeFriendRoom',()=>service.action('close'));bind('leaveFriendRoom',leave);bindShare();
 document.querySelectorAll('.remove-player').forEach(b=>b.addEventListener('click',()=>service.action('kick',{playerId:b.dataset.player}).catch(error)));
 ['roomGame','roomMode','roomDifficulty','roomQuestionTime','roomContinent','roomQuestions'].forEach(id=>document.getElementById(id)?.addEventListener('change',()=>{const c={...data.config,family:document.getElementById('roomGame').value,variant:document.getElementById('roomMode').value,difficulty:document.getElementById('roomDifficulty')?.value||data.config.difficulty,questionTime:Number(document.getElementById('roomQuestionTime')?.value||data.config.questionTime||20),region:document.getElementById('roomContinent')?.value||data.config.region,questionCount:Number(document.getElementById('roomQuestions')?.value||data.config.questionCount)};service.action('settings',{config:c}).catch(error);}));
 }
 function finalResults(data,waiting=false){const own=data.result;const winner=data.standings.filter(p=>p.rank===1&&!p.dnf);const finished=data.standings.filter(p=>p.finished&&!p.dnf);const fastest=[...finished].filter(p=>p.average!==null).sort((a,b)=>a.average-b.average)[0];const accurate=[...finished].sort((a,b)=>b.accuracy-a.accuracy)[0];const longest=[...finished].sort((a,b)=>b.bestStreak-a.bestStreak)[0];
 const questionGame=own&&own.config.family!=='conquest';
 shell(`<h2>${waiting?"You’re done":data.kind==='challenge'?'Friend Challenge':'Final results'}</h2>${waiting?`<p>Waiting for ${data.standings.filter(p=>!p.finished).length} players…</p>`:winner.length?`<div class="podium">${winner.length>1?'TIED WINNERS':'🥇'}<strong>${winner.map(p=>esc(p.name)).join(' & ')}</strong></div>`:''}${!waiting?'<div class="friend-podium">'+data.standings.filter(p=>!p.dnf&&p.rank<=3).map(p=>'<div><span>'+['🥇','🥈','🥉'][p.rank-1]+'</span><strong>'+esc(p.name)+'</strong><small>'+p.score.toLocaleString()+' points</small></div>').join('')+'</div>':''}<div>${standings(data)}</div>${own?`<h3>Your result</h3><div class="your-stats"><span><b>${own.score}</b> Score</span><span><b>${own.correct}</b> Correct</span><span><b>${own.wrong}</b> ${questionGame?'Missed':'Incorrect entries'}</span><span><b>${own.accuracy}%</b> Accuracy</span><span><b>${own.bestStreak}</b> Best streak</span><span><b>${own.averageResponseTime?.toFixed(1)||'—'}s</b> Average correct answer</span></div>${questionGame?`<p class="friend-note">Accuracy is correct questions divided by questions played. ${own.incorrectAttempts||0} incorrect attempts affected the score.</p>`:''}`:''}${!waiting&&fastest?`<p class="friend-note">Fastest: ${esc(fastest.name)} · ${fastest.average.toFixed(1)}s<br>Best accuracy: ${esc(accurate.name)} · ${Math.round(accurate.accuracy)}%<br>Longest streak: ${esc(longest.name)} · ${longest.bestStreak}</p>`:''}<p class="friend-note">Ranking: score, accuracy, average response time, then fewer mistakes. Exact ties share a place. DNF players follow finishers.</p>${!waiting&&data.kind==='live'&&data.hostPlayerId===data.you?'<button id="rematch" class="primary-button">Rematch / Change Game</button>':''}${data.kind==='challenge'&&!data.game?'<button id="playChallenge" class="primary-button">Play Challenge · one official attempt</button>':''}<button id="copyInvite">Share Results / Copy Link</button>${navigator.share?'<button id="nativeShare">Share</button>':''}<button id="leaveFriendRoom">${data.kind==='challenge'?'Play Again Solo / Leave Challenge':'Leave Room'}</button>`);
 bind('rematch',()=>service.action('rematch'));bind('playChallenge',()=>service.action('attempt'));bind('leaveFriendRoom',leave);bindShare();
 }
 async function leave(){await service.leave();gameController.exitRemote();latest=null;activeGameKey=null;board.hidden=true;countdown.hidden=true;panel.hidden=true;if(!window.CountryMemoryRetained?.requestHostNavigation({type:'home'}))history.replaceState(null,'',location.pathname);}
 async function copyLink(){const link=service.invite();try{await navigator.clipboard.writeText(link);connection.textContent='Invite link copied';connection.hidden=false;setTimeout(()=>connection.hidden=true,1800);}catch{const field=panel.querySelector('.invite-link');if(field){field.focus();field.select();}else throw new Error('Copy this link: '+link);}}
 function bindShare(){bind('copyInvite',copyLink);bind('nativeShare',()=>navigator.share({title:'Country Memory Map · Friend challenge',text:'Join my private geography game.',url:service.invite()}));}
 function connectGame(data){const key=data.match.id+':'+data.game.startedAt;if(activeGameKey!==key){activeGameKey=key;board.open=innerWidth>760;questionKey=null;lastEvent=null;gameController.connectRemote({now:()=>service.now(),submit,finish:()=>service.action('finish').catch(error)});}
  const qkey=data.game.currentQuestion?.id||key;if(questionKey!==qkey){questionKey=qkey;questionShownAt=performance.now();}
  if(data.event?.type==='correct'&&lastEvent!==data.event.id){lastEvent=data.event.id;if(data.config.family==='conquest')questionShownAt=performance.now();}
  gameController.renderRemote(data);
 }
 async function submit(kind,value){if(submitBusy||!latest?.game||(kind==='text'&&!String(value).trim()))return false;submitBusy=true;gameController.blockRemote(true);const payload={kind,value,matchId:latest.match.id,questionId:latest.game.currentQuestion?.id||null,seq:latest.nextSeq,responseTime:Math.max(0,(performance.now()-questionShownAt)/1000)};try{await service.action('answer',payload);return true;}catch(e){connection.textContent=e.message;connection.hidden=false;return false;}finally{submitBusy=false;if(latest?.game)gameController.renderRemote(latest);}}
 function render(data){if(data.error){if(hosted)window.CountryMemoryRetained?.requestHostNavigation({type:'multiplayer-room'});shell(`<h2>${esc(data.message)}</h2><button id="expiredNew">Create New Room</button>`);bind('expiredNew',()=>{service.session=null;service.save();home();});board.hidden=true;countdown.hidden=true;gameController.blockRemote(true);return;}
 latest=data;const playing=data.game?.gameStatus==='playing'&&service.now()>=data.game.startedAt;
 if(hosted&&service.session?.code===data.code)window.CountryMemoryRetained?.requestHostNavigation({type:'multiplayer-room',room:data.code});
 const countdownActive=data.game&&data.game.gameStatus==='playing'&&service.now()<data.game.startedAt;
 const key=JSON.stringify([data.kind,data.state,data.config,data.players,data.standings,data.you,!!data.game,data.game?.gameStatus,data.notice]);
 if(countdownActive){panel.hidden=true;board.hidden=false;countdown.hidden=false;return;}
 countdown.hidden=true;
 if(playing){panel.hidden=true;board.hidden=false;document.getElementById('liveRows').innerHTML=standings(data);connectGame(data);if(submitBusy)gameController.blockRemote(true);const lead=data.standings[0]?.id;if(lastLeader&&lead!==lastLeader&&Date.now()-noticeAt>8000){connection.textContent=data.standings[0].name+' took the lead';connection.hidden=false;noticeAt=Date.now();setTimeout(()=>connection.hidden=true,2000);}lastLeader=lead;return;}
 if(data.game?.gameStatus==='ended'&&activeGameKey)gameController.renderRemote(data);
 if(key===renderKey)return;renderKey=key;
 board.hidden=true;
 if(data.state==='CLOSED'){shell('<h2>This room is closed</h2><button id="leaveFriendRoom">Back to games</button>');bind('leaveFriendRoom',leave);gameController.blockRemote(true);return;}
 if(data.kind==='challenge'){finalResults(data);return;}
 if(data.state==='RESULTS'){finalResults(data);return;}
 if(data.state==='PLAYING'&&data.game?.gameStatus==='ended'){finalResults(data,true);return;}
 lobby(data);
 }
 setInterval(()=>{if(!latest?.game)return;const seconds=Math.ceil((latest.game.startedAt-service.now())/1000);if(seconds>0&&latest.game.gameStatus==='playing'){countdown.textContent=seconds;countdown.hidden=false;}else if(!countdown.hidden){countdown.hidden=true;renderKey='';render(latest);service.poll();}},80);
 window.Friends={challenge(replay){pendingReplay=replay;shell('<h2>Challenge your friends</h2><p>The same questions and rules. Up to 8 players, whenever they’re ready.</p>'+nameField()+'<button id="createAsync" class="primary-button">Create Challenge Link</button><button id="cancelChallenge">Back</button>');bind('createAsync',()=>service.create(nameValue(),pendingReplay));bind('cancelChallenge',()=>panel.hidden=true);}};
 window.CountryMemoryMultiplayer={
  async open({room}={}){await service.resume();if(room)return joinScreen(room);if(service.session){await service.poll();if(service.room)return;}home();},
  suspend(){service.suspend();panel.hidden=true;board.hidden=true;countdown.hidden=true;if(activeGameKey)gameController.exitRemote();else gameController.blockRemote(true);}
 };
 entry.addEventListener('click',()=>{if(!window.CountryMemoryRetained?.requestHostNavigation({type:'multiplayer'}))home();});
 const invited=new URL(location.href).searchParams.get('room');if(!hosted&&!invited&&service.session)service.poll();if(invited)joinScreen(invited.toUpperCase()).catch(e=>{shell('<h2>Could not open this room</h2><button id="newRoom">Create New Room</button>');error(e);bind('newRoom',home);});
 }
 boot();
})();
