const { test } = require('node:test');
const assert = require('node:assert/strict');
const {Engine,LocalProfile,calculateScore,MODES,TYPES,normalize} = require('../game-core.js');
const countries = Array.from({length:30},(_,i)=>({country_id:`C${i}`,canonical_name:`Country ${i}`,accepted_names:[`Country ${i}`,`alias${i}`],continent:i<15?'Africa':'Asia',countryLocationDifficulty:i%4+1,capitalDifficulty:4-i%4,capital:[{name:`Capital ${i}`,aliases:[`city${i}`],role:'capital'},...(i===0?[{name:'Second capital',aliases:['Second'],role:'legislative capital'}]:[])]}));
function game(config={family:'conquest',variant:'relaxed'}) {let time=0;const events=[];const engine=new Engine(countries,{now:()=>time,random:()=>0.42,onEvent:e=>events.push(e)});engine.start(config);return {engine,events,advance:ms=>{time+=ms;engine.tick();},at:ms=>{time=ms;},now:()=>time};}
function answer(engine) {const q=engine.state.currentQuestion;if(q.type===TYPES.CAPITAL_TYPING)engine.submitText(engine.byId.get(q.countryId).capital[0].name);else engine.submitCountry(q.countryId);}
test('exact speed and streak boundaries, normalized aliases',()=>{assert.equal(calculateScore(true,1.99,1),130);assert.equal(calculateScore(true,2,1),120);assert.equal(calculateScore(true,4,1),110);assert.equal(calculateScore(true,7,1),110);assert.equal(calculateScore(true,7.01,1),100);assert.equal(calculateScore(true,1,5),137);assert.equal(calculateScore(true,1,10),143);assert.equal(calculateScore(true,1,20),156);assert.equal(calculateScore(true,1,40),169);assert.equal(normalize('  Côte d’Ivoire '),'cote d ivoire');assert.equal(normalize('Saint Lucia'),normalize('St. Lucia'));});
test('aliases count once; duplicates never break streak or earn points; invalid only on submit',()=>{const {engine:e,advance}=game();advance(1000);e.submitText('ALIAS0');assert.equal(e.state.score,130);e.submitText('Country 0');assert.equal(e.state.score,130);assert.equal(e.state.streak,1);assert.equal(e.state.wrongAnswers,0);advance(9000);assert.equal(e.state.streak,1);e.submitText('alias1');assert.equal(e.state.score,230);e.submitText('invalid');assert.equal(e.state.streak,0);assert.equal(e.state.wrongAnswers,1);});
test('every World Conquest variant shares its rules and starts',()=>{for(const variant of Object.keys(MODES.conquest)){const {engine:e}=game({family:'conquest',variant,region:'Africa'});e.submitText('alias0');assert.equal(e.state.correctAnswers,1);assert.equal(e.state.lives,variant==='sudden'?3:null);assert.equal(e.state.remainingTime,variant==='blitz'?60:variant==='sprint'?180:null);}});
test('Sudden Death ends on third invalid submission, duplicates cost no life',()=>{const {engine:e}=game({family:'conquest',variant:'sudden'});e.submitText('alias0');e.submitText('alias0');assert.equal(e.state.lives,3);e.submitText('wrong');e.submitText('wrong2');assert.equal(e.state.gameStatus,'playing');e.submitText('wrong3');assert.equal(e.state.gameStatus,'ended');assert.equal(e.result.mistakes.length,3);e.submitText('alias1');assert.equal(e.state.correctAnswers,1);});
test('countdowns reject input at the deadline even before the next UI tick',()=>{for(const [variant,duration] of [['sprint',180000],['blitz',60000]]){const {engine:e,at}=game({family:'conquest',variant});at(duration);e.submitText('alias0');assert.equal(e.state.gameStatus,'ended');assert.equal(e.state.correctAnswers,0);assert.equal(e.result.elapsedTime,duration/1000);assert.equal(e.state.remainingTime,0);}});
test('region scope, completion and milestone events',()=>{const {engine:e,events}=game({family:'conquest',variant:'continent',region:'Africa'});e.submitText('alias20');assert.equal(e.state.correctAnswers,0);for(let i=0;i<15;i++)e.submitText(`alias${i}`);assert.equal(e.state.gameStatus,'ended');assert.equal(e.result.total,15);assert.equal(e.result.completed,true);assert.ok(events.some(x=>x.type==='milestone'&&x.count===10));});
test('all six question variants play and finish; classic has 10 of each type',()=>{for(const family of ['find','capital'])for(const variant of Object.keys(MODES[family])){const {engine:e,advance}=game({family,variant,region:'Africa',difficulty:'medium'});for(let n=0;n<20&&e.state.gameStatus==='playing';n++){answer(e);advance(701);}if(variant==='blitz')advance(60000);assert.equal(e.state.gameStatus,'ended');assert.equal(e.state.correctAnswers,20);if(family==='capital'&&variant!=='blitz'){assert.equal(e.result.questionHistory.filter(q=>q.type===TYPES.CAPITAL_TYPING).length,10);assert.equal(e.result.questionHistory.filter(q=>q.type===TYPES.CAPITAL_COUNTRY_CLICK).length,10);}}});
test('question penalties: -25, -50, third reveals; no negative-score clamping',()=>{const {engine:e,advance,events}=game({family:'find',variant:'standard'});e.submitCountry('not-target');assert.equal(e.state.score,-25);e.submitCountry('not-target');assert.equal(e.state.score,-75);e.submitCountry('not-target');assert.equal(e.state.score,-75);assert.equal(e.state.currentQuestion.resolved,true);assert.equal(e.state.wrongAnswers,3);assert.equal(e.state.questionHistory.length,1);assert.ok(events.some(x=>x.type==='reveal'));advance(701);assert.equal(e.state.questionNumber,2);});
test('timeout records a miss, resets streak, moves after 700ms and cannot be answered late',()=>{const {engine:e,advance,at}=game({family:'find',variant:'standard'});const id=e.state.currentQuestion.countryId;at(10000);e.submitCountry(id);assert.equal(e.state.correctAnswers,0);assert.equal(e.state.wrongAnswers,1);assert.equal(e.state.currentQuestion.resolved,true);advance(699);assert.equal(e.state.questionNumber,1);advance(1);assert.equal(e.state.questionNumber,2);});
test('timer continues in background and time expiry during feedback cannot spawn a question',()=>{const {engine:e,at,advance}=game({family:'find',variant:'blitz'});at(59500);e.tick();advance(701);assert.equal(e.state.gameStatus,'ended');assert.equal(e.state.remainingTime,0);assert.equal(e.result.elapsedTime,60);});
test('multiple capitals and aliases are accepted only for the target country',()=>{const {engine:e}=game({family:'capital',variant:'classic',practiceIds:['C0']});e.submitText('Second');assert.equal(e.state.correctAnswers,1);const other=game({family:'capital',variant:'classic',practiceIds:['C0']}).engine;other.submitText('Capital 1');assert.equal(other.state.correctAnswers,0);assert.equal(other.state.wrongAnswers,1);});
test('difficulty fields are independent; continent question pools stay in scope',()=>{const find=game({family:'find',variant:'continent',region:'Africa',difficulty:'expert'}).engine;const capital=game({family:'capital',variant:'continent',region:'Africa',difficulty:'expert'}).engine;assert.ok(find.pool.every(c=>c.countryLocationDifficulty===4&&c.continent==='Africa'));assert.ok(capital.pool.every(c=>c.capitalDifficulty===4&&c.continent==='Africa'));assert.notDeepEqual(find.pool.map(c=>c.country_id),capital.pool.map(c=>c.country_id));});
test('results separate question accuracy from incorrect attempts and retain retry practice targets',()=>{const {engine:e,advance}=game({family:'find',variant:'standard'});const id=e.state.currentQuestion.countryId;e.submitCountry('bad');advance(1000);answer(e);advance(701);e.finish();assert.equal(e.result.correct,1);assert.equal(e.result.total,2);assert.equal(e.result.accuracy,50);assert.equal(e.result.wrong,1);assert.equal(e.result.missedQuestions,1);assert.equal(e.result.incorrectAttempts,2);assert.ok(e.result.missedCountries.includes(id));assert.equal(e.result.averageResponseTime,1);const practice=game({family:'find',variant:'standard',practiceIds:e.result.missedCountries}).engine;assert.equal(practice.pool.length,e.result.missedCountries.length);assert.equal(practice.state.questionLimit,e.result.missedCountries.length);});
test('a 17 of 20 round reports 85% accuracy and 3 missed questions',()=>{const {engine:e,advance}=game({family:'find',variant:'standard'});for(let n=0;n<17;n++){answer(e);advance(701);}for(let n=0;n<3;n++){advance(10000);advance(701);}assert.equal(e.result.correct,17);assert.equal(e.result.total,20);assert.equal(e.result.accuracy,85);assert.equal(e.result.wrong,3);assert.equal(e.result.missedQuestions,3);assert.equal(e.result.incorrectAttempts,3);});
test('persistence tolerates corrupt/denied storage, scopes bests, keeps recent results',()=>{const data=new Map();const storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)};const profile=new LocalProfile(storage);const {engine:e}=game({family:'conquest',variant:'sprint'});e.submitText('alias0');e.finish();profile.record(e.result);assert.equal(e.result.personalBest,true);assert.equal(new LocalProfile(storage).data.recent.length,1);const slower={...e.result,score:0,personalBest:false};profile.record(slower);assert.equal(slower.personalBest,false);const denied=new LocalProfile({getItem(){throw Error();},setItem(){throw Error();}});denied.record(e.result);assert.equal(denied.available,false);const corrupt=new LocalProfile({getItem:()=>'{nope'});assert.equal(corrupt.data.recent.length,0);});
